### ISSUE TITLE
Not sure how this text message is implemented

### ISSUE THREAD

**Issue by colten1007** [sytaxus/SMSend-Anon-SMS-Sender#1]
Not sure how this text message is implemented

**Comment by cmdsnr** [comment]
What issues are you facing exactly? Everything that's needed to know is all explained in the description.

I will release a video on how-to-use as well, but until then, If you're facing an error, be specific please.

**Comment by colten1007** [comment]
I'm sorry I didn't make myself clear. I didn't understand how to log in to VPN or what brand of VPN to log in to. Do you have telegram

**Comment by cmdsnr** [comment]
Ah, I see, the program is solely focused on **openVPN configuration files**, and needs an **openVPN configuration file**, which uses a .ovpn file extension. Firstly, no I do not use Telegram, however you can contact me using Matrix: `@sysnr:matrix.org` , if you don't have an account, feel free to create one at: `https://app.element.io/` 

**How to get your OpenVPN Configs and Credentials:**
`Example`: Login to https://account.protonvpn.com/account
If you don't have a protonVPN account, just make one, unless the vpn service that you prefer has openvpn configs already, like nordvpn etc, but for now let's assume protonvpn. Scroll down to "OpenVPN / IKEv2 username" copy both the username and password, then when you run `setup.sh` , it will ask you: `Do you want to configure or reconfigure the auth.txt file? (y/n)` , simply type 'y' , then enter your openVPN username and password that you just copied from `https://account.protonvpn.com/account`.
**OR**
You can ignore and instead just manually open up or create a new `auth.txt` file, then in the very first line, paste in your openvpn configuration username, in the second line, your openvpn configuration password.

**Note**: Make sure you place all of your vpn configs (with the .ovpn extension) in the **same** directory.

So, to sum it all up, you need to use OpenVPN configuration files from the vpn service of your choice, in our example case, ProtonVPN. You can get the configuration files at https://account.protonvpn.com/downloads , make sure the platform is selected as `GNU/Linux` , you can use either TCP or UDP protocol, then download your configs.

Hope this helps,

Cheers.

**Comment by colten1007** [comment]
Ha, thank you for your reply. I will contact your matrix later. I have a question: Will the use of VPN not exhaust the node's one sending opportunity? Or will it be better to use proxy to send one message and replace it with another proxy

**Comment by cmdsnr** [comment]
You need to use **different** vpns **each time**, the good news is that the tool already handles that part, which is switching through vpns automatically each time, so you won't have to do much. The tool will link each phone number with a random vpn from the vpn directory (where the .ovpn configs are located), then will keep switching connections each time. I recommend that you make sure that the amount of phone numbers is equal to the amount of openvpn configs.

All you need to do is have all of your openvpn configuration files in the same directory with each extension being a `.ovpn`. And that's it! Finally, just specify the directory of where the vpn configs are, and assuming you already did the `auth.txt` / openvpn credentials (username and password) setup, you should be good to go.

Cheers.

**Comment by colten1007** [comment]
I'm curious what the maximum amount you tested was

**Comment by cmdsnr** [comment]
I used international VOIP numbers and my personal number as test, but the maximum amount I tried was around 27 numbers, and yes it worked just fine. Try avoiding abusing it too much through. Since it uses the textbelt free api key, which might have limitations sometimes. You can always purchase your own API key from textbelt if you'd like to get rid of the limitation though.

**Comment by colten1007** [comment]
I understand. Thank you for your help. I think I should buy API to be better    Cheers

**Comment by cmdsnr** [comment]
If you're planning a large scale sms campaign then it's probably worth it. 

Thanks for checking out SMSend!

Cheers.
